version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www:rw
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql:3306
      DB_USER: dev
      DB_PASSWORD: 123456
      DB_NAME: myapp
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: sakila
    volumes:
      - ./both.sql:/docker-entrypoint-initdb.d/schema.sql